import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'
import {copyFileSync} from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const devPlugins = '../obsidian-develop-vault/.obsidian/plugins/cycle-in-sidebar'
esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	watch: {
		onRebuild(error, result) {
			const files = ['main.js', 'manifest.json', 'styles.css'];
			files.forEach(file => {
				console.log('writes to', devPlugins + '/' + file)
				copyFileSync(file, devPlugins + '/' + file);
			})
		}
	},
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
}).then(() => {
}).catch(() => process.exit(1));
