import { defineConfig } from 'rollup';
import typescript from '@rollup/plugin-typescript';
import copy from 'rollup-plugin-copy';

export default defineConfig({
	input: 'main.ts',
	output: {
		file: 'main.js',
		format: 'cjs',
		sourcemap: process.env.NODE_ENV === 'production' ? false : 'inline',
		banner: `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source, please visit the github repository of this plugin
*/
`,
	},
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...Object.keys(process.binding('natives'))
	],
	plugins: [
		typescript({
			target: 'es2018',
			skipLibCheck: true,
			noEmitOnError: true,
		}),
		copy({
			targets: [
				{ src: 'main.js', dest: 'test-vault/.obsidian/plugins/obsidian-cycle-in-sidebar-plugin/' },
				{ src: 'manifest.json', dest: 'test-vault/.obsidian/plugins/obsidian-cycle-in-sidebar-plugin/' },
				{ src: 'styles.css', dest: 'test-vault/.obsidian/plugins/obsidian-cycle-in-sidebar-plugin/' },
			],
			hook: 'writeBundle',
		}),
	],
});
